proxy-providers: {}
proxy-groups: []
rules: []
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - system
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
log-level: warning
mode: global
proxies:
  - keepalive: 25
    name: Hetzner
    port: 51820
    private-key: eM63h7vj3iICKECtBpAEDN6j7a8r0qo5g17oyIauO1E=
    public-key: la4wE0bl0+BIVzZcNVJl2PrMJKAgeGFYyylSXWt6E2o=
    server: 167.235.68.149
    type: wireguard
    ip: 10.6.0.2
    dns: null
    preshared-key: WMN4w1FEdHzeNACJzbNEfulmsECFNaTV2GFXlRcqh2g=
