proxy-providers: {}
proxy-groups: []
rules: []
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - system
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
log-level: warning
mode: global
proxies:
  - ip: 10.66.66.11
    keepalive: 25
    name: Vdsina
    port: 61590
    preshared-key: 2NvEjCzYxlk7tl9Pj32w191+rx42lHXlUnIdIGd/+ZE=
    private-key: AMsSPV7QtrjOo4dDq2W/as/WI93TJMJxv/qtG3ZS1mw=
    public-key: k0ComhrLnDEcly4g7aSetyo+PBNRxVCK6dwMMYdFUAA=
    server: 77.238.246.167
    type: wireguard
